{% set version = "1.1.0" %}

package:
  name: sng
  version: {{ version }}

source:
  - url: http://sourceforge.net/projects/sng/files/sng-{{ version }}.tar.gz
    sha256: 119c55870c1d1bdc65f7de9dbc62929ccb0c301c2fb79f77df63f5d477f34619
  - folder: pngsuite
    url: http://www.schaik.com/pngsuite/PngSuite-2017jul19.tgz
    sha256: 0294b244c95a8342c01b00010cf34abdcabc7c6a34fd0fe1bd963917537bfdc8

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf  # [linux]
    - automake  # [linux]
    - make  # [linux]
  host:
    - libpng
    - netpbm

test:
  commands:
    - sng -V
    - sng -V | grep -iE "sng version {{ version.replace(".", "\.") }}"

about:
  home: https://sng.sourceforge.net
  summary: Enable lossless editing of PNGs via a textual representation.
  description: |
    SNG (Scriptable Network Graphics) is a minilanguage designed specifically to
    represent the entire contents of a PNG (Portable Network Graphics) file in an
    editable form. Thus, SNGs representing elaborate graphics images and ancillary
    chunk data can be readily generated or modified using only text tools.

    SNG is implemented by a compiler/decompiler called sng that losslessly
    translates between SNG and PNG.
  license: Zlib
  license_file: COPYING

extra:
  recipe-maintainers:
    - bollwyvl
