# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.1.2"

package:
  name: sng
  version: ${{ version }}

source:
  - url: https://sourceforge.net/projects/sng/files/sng-${{ version }}.tar.gz
    sha256: e6938a66ce3b6fafb0c6e6b809f8ddf662c6a962279278c4a627924761336f93
  - url: http://www.schaik.com/pngsuite/PngSuite-2017jul19.tgz
    sha256: 0294b244c95a8342c01b00010cf34abdcabc7c6a34fd0fe1bd963917537bfdc8
    target_directory: pngsuite

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: linux
      then:
        - autoconf
        - automake
        - make
  host:
    - libpng
    - netpbm

tests:
  - script:
      - sng -V
      - sng -V | grep -iE "sng version ${{ version | replace(".", "\\.") }}"

about:
  summary: Enable lossless editing of PNGs via a textual representation.
  description: |
    SNG (Scriptable Network Graphics) is a minilanguage designed specifically to
    represent the entire contents of a PNG (Portable Network Graphics) file in an
    editable form. Thus, SNGs representing elaborate graphics images and ancillary
    chunk data can be readily generated or modified using only text tools.

    SNG is implemented by a compiler/decompiler called sng that losslessly
    translates between SNG and PNG.
  license: Zlib
  license_file: COPYING
  homepage: https://sng.sourceforge.net
  repository: https://sourceforge.net/p/sng/code/ci/master/tree/

extra:
  recipe-maintainers:
    - bollwyvl
